config/routes.rb
Rails.application.routes.draw do
  
  root 'memories#index'
  resources :memories do
    resources :comments 
    member do
        put 'like', to: "memories#like"
        put 'unlike', to: "memories#unlike"
    end
  end
  
  resources :comments do
    resources :comments
  end
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  validates :user_id, presence: true
  default_scope -> {order(updated_at: :desc)}
  validates :body, length: { minimum: 1, maximum: 100 }
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  validates :user_id, presence: true
  validates :title, length: { minimum: 3, maximum: 30 }
  validates :body, length: { minimum: 3, maximum: 1000 }
  default_scope -> {order(updated_at: :desc)}
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :memories
  has_many :comments
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  # before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def new
    @comment = Comment.new
  end
    
  def create
    session[:return_to] ||= request.referer
    @comment = @commentable.comments.new(comment_params)
    @comment.user_id = current_user.id
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to session.delete(:return_to), notice: 'Your comment was successfully posted!' }
        format.js
      else
        format.html { redirect_to session.delete(:return_to), danger: 'Enter at least 1 characters' }
        format.js
      end
    end
      
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
  # def require_same_user
  #   if current_user != @comment.user
  #     flash[:warning] = "You can edit or delete your own Comments only"
  #     redirect_to root_path
  #   end
  # end
  
  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Memory.find_by_id(params[:memory_id]) if params[:memory_id]
  end
  
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /memories
  # GET /memories.json
  def index
    @memories = Memory.all
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
  end

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories
  # POST /memories.json
  def create
    @memory = Memory.new(memory_params)
    @memory.user_id = current_user.id

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: 'Memory was successfully created.' }
        format.json { render :show, status: :created, location: @memory }
        format.js
      else
        format.html { render :new }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /memories/1
  # PATCH/PUT /memories/1.json
  def update
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to @memory, notice: 'Memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @memory.destroy
    respond_to do |format|
      format.html { redirect_to memories_url, notice: 'Memory was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end
  
  def like
    session[:return_to] ||= request.referer
    @memory.liked_by current_user
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to) }
      format.js
    end
  end
 
  def unlike
    session[:return_to] ||= request.referer
    @memory.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to) }
      format.js
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end
    
    def require_same_user
      if current_user != @memory.user
        flash[:warning] = "You can edit or delete your own articles only"
        redirect_to root_path
      end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_params
      params.require(:memory).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/comments/_add_comment.html.erb
<div class="well col-md-10">
  <p><%= comment.body %></p>
  <p>
    <small>
      Created: <%= time_ago_in_words(comment.created_at) %>
      ago by <%= comment.user.email.split('@') [0].capitalize %>
    </small>
  </p>
</div>

app/views/comments/_comment.html.erb
<%= render 'comments/add_comment', comment: comment%>
<%= render 'comments/form', obj: comment%>

<div class="row col-md-11 col-md-offset-1">
  <%= render partial: 'comments/comment', collection: comment.comments %>
</div>

app/views/comments/_comments.html.erb
<%= render 'comments/form', obj: obj %>
<div class="row">
  <%= render(partial: 'comments/comment', collection: obj.comments) %>
</div>

app/views/comments/_form.html.erb
<div class='col-md-12'>
  <div class='row'>
    <%= form_for [obj, Comment.new], remote: true do |f| %>
      <div class="control-label col-md-10">
        <%= f.text_area :body, placeholder: "Add your comment" , id: "clr" %>
      </div>
      <div class="col-sm-offset-2 col-md-10">
        <%= f.submit "Add Comment"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$('.show-it').prepend("<%= j render 'comments/add_comment', comment: @comment %>");
$('#clr').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Memory" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "My Memory", root_path, class: "navbar-brand"  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user.present? %>
              <li><a><i class="fa fa-user" style="color:lime"></i>
              <strong><%= current_user.email.split('@') [0].capitalize %></strong></a></li>
            <%else%>
              <li><a><i class="fa fa-user" style="color:red"></i>
              <strong>Guest</strong></a></li>
            <%end%>
            
            <% if current_user %>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete  %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--<div class="col-lg-3">-->
        <!--  <div class="well sidebar-nav">-->
        <!--    <h3>Sidebar</h3>-->
        <!--    <ul class="nav nav-list">-->
        <!--      <li class="nav-header">Sidebar</li>-->
        <!--      <li><#%= link_to "Link1", "/path1"  %></li>-->
        <!--      <li><#%= link_to "Link2", "/path2"  %></li>-->
        <!--      <li><#%= link_to "Link3", "/path3"  %></li>-->
        <!--    </ul>-->
        <!--  </div><!--/.well -->
        <!--</div><!--/span-->
      <!--</div><!--/row-->
      
    </div>

    <footer>
      <p>&copy; Company 2019</p>
    </footer>

    <!-- /container -->

  </body>
</html>

app/views/memories/_fav_link.html.erb
<%= link_to like_memory_path(@memory), method: :put, remote: true, id: "like-#{memory.id}" do %>
  <i class="fa fa-heart-o fa-2x" style="color:black"></i>
<% end %>

app/views/memories/_form.html.erb
<div class='row'>
  <div class='col-md-12'>

    <%= form_with(model: memory) do |form| %>
      <% if memory.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(memory.errors.count, "error") %> prohibited this memory from being saved:</h2>
    
          <ul>
          <% memory.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <div class="control-label col-md-2">
          <%= form.label :title %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :title, id: :memory_title %>
        </div>
      </div>
    
      <div class="field">
        <div class="control-label col-md-2">
          <%= form.label :body , "Description" %>
        </div>
        <div class="col-md-10">
          <%= form.text_area :body, rows: 13, placeholder: "Post your Memories", autofocus: true, id: :memory_body %>
        </div>
      </div>
    
      <div class="actions">
        <div class="col-sm-offset-2 col-md-10">
          <%= form.submit class: 'btn btn-primary btn-lg'%>
        </div>
      </div>
    <% end %>
    
  </div>
</div>

app/views/memories/_memories.html.erb
<% @memories.each do |memory| %>
  <%= render memory %>
<%end%>

app/views/memories/_unfav_link.html.erb
<%= link_to unlike_memory_path(memory), method: :put, remote: true, id: "unlike-#{memory.id}" do %>
  <i class="fa fa-heart fa-2x" style="color:green"></i>
<% end %>

app/views/memories/create.js.erb
$('#new-mem form').remove();
$('#new-mem a').show();
$('#new-data').prepend("<%= j render @memory  %>");

app/views/memories/destroy.js.erb
$('.delete-data').bind('ajax:success', function() {
  $(this).closest('div').fadeOut(500);
});

app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form', memory: @memory %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

app/views/memories/edit.js.erb
$('.edit-data').bind('ajax:success', function() {
  $(this).closest("div").hide();
  $('#new-mem a').hide();
  $("html, body").animate({ scrollTop: 0 }, "slow");
  $('#edit-mem').html("<%= j render 'form', memory: @memory %>");
});

app/views/memories/index.html.erb
<h1 align="center">Listing all the Memories</h1>
<div class="row">
  <div class="col-xs-8 col-xs-offset-5" id="new-mem">
   <%= link_to 'New Memory', new_memory_path , remote: true %>
  </div>
</div>

<div class="row" >
  <div class="col-xs-8 col-xs-offset-5" id="edit-mem">
  
  </div>
</div>

<div id="new-data">
  <%= render 'memories', obj: @memories %>
</div>

app/views/memories/new.html.erb
<h1 align="center"> Create a new memory</h1>

<%= render 'form', memory: @memory %>

<%= link_to 'Back', memories_path %>

app/views/memories/new.js.erb
$('#new-mem a').hide().parent().append("<%= j render 'form', memory: @memory %>");

app/views/memories/show.html.erb
<h2 align="center"><%=@memory.title.capitalize%></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <div class="row center">
    <div class="col-md-4 col-md-offset-4">
      <%= simple_format(@memory.body) %>
    </div>
    
    <div class="col-md-12">
      <strong><%= @memory.user.email.split('@') [0].capitalize %></strong>
      Created: <%= time_ago_in_words(@memory.created_at) %> ago and recently updated this memory : <%= time_ago_in_words(@memory.updated_at) %> ago!
    </div>
    
    <div class="col-md-12 votes">
    <% if current_user.liked? @memory %>
        <%= render 'unfav_link', memory: @memory %>
      <% else %>
        <%= render 'fav_link', memory: @memory %>
      <% end %>
      <span class="count"><%= @memory.votes_for.size %></span>
    </div>  
    <div class="col-md-12">
    <% if current_user == @memory.user %>
      <%= link_to 'Edit', edit_memory_path(@memory) %> |
    <%end%>
    <%= link_to 'Back', memories_path %>
    </div>
  </div>
</div>
<div class="col-md-8 col-md-offset-2">
  <div class="row" id="no">
    <h3 id="cmt-count"><a> <%=pluralize(@memory.comments.count, "Comment")%> </a></h3>
      <div class="show-it" style="display: none;">
        <%= render 'comments/comments', obj: @memory%>
      </div>
  </div>
</div>

app/views/memories/unlike.js.erb
$("#unlike-<%= @memory.id %>").bind('ajax:success', function(){
  $(this).replaceWith('<%= j render 'fav_link', memory: @memory %>');
  $('.votes').find('.count').html("<%= j @memory.votes_for.size.to_s %>");
});

app/views/memories/update.js.erb
$('#edit-mem form').remove();
$('#new-mem a').show();
$('#new-data').prepend("<%= j render @memory %>");